"""
Audit Report Generator

Generates structured, UK-regulation-aligned audit reports.
Automatically includes fairlearn/aif360 metrics in the report if they were computed.
"""

import os
from datetime import datetime


class AuditReportGenerator:

    def __init__(self, company_name="UK SME Ltd", job_role="General Vacancy",
                 recruitment_round=None, auditor_name="AI Audit Toolkit v1.0"):
        self.company_name      = company_name
        self.job_role          = job_role
        self.recruitment_round = recruitment_round or datetime.now().strftime("%Y-%m")
        self.auditor_name      = auditor_name
        self.generated_at      = datetime.now().strftime("%d %B %Y, %H:%M")

    def generate(self, model_info, data_audit_results, bias_results,
                 explainability_summary, candidate_examples=None, output_path=None):

        sections = [
            self._header(),
            self._model_card(model_info),
            self._data_audit_section(data_audit_results),
            self._fairness_section(bias_results),
            self._explainability_section(explainability_summary),
            self._recommendations(bias_results, data_audit_results),
            self._regulatory_references(),
        ]

        if candidate_examples:
            sections.append(self._candidate_appendix(candidate_examples[:5]))

        sections.append(self._footer())
        report = "\n\n---\n\n".join(sections)

        if output_path:
            os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(report)
            print(f"Report saved: {output_path}")

        return report

    def _header(self):
        return f"""# AI Recruitment Audit Report

**Company:** {self.company_name}
**Job Role:** {self.job_role}
**Recruitment Round:** {self.recruitment_round}
**Auditor:** {self.auditor_name}
**Generated:** {self.generated_at}

> This report has been automatically generated by the XAI Audit Toolkit in accordance with
> ICO guidance on AI transparency and the Equality Act 2010. It should be reviewed by a
> qualified HR professional or legal advisor before being used for compliance purposes."""

    def _model_card(self, model_info):
        features = "\n".join(f"  - {f}" for f in model_info.get("features", []))
        return f"""## 1. Model Card

| Field | Value |
|-------|-------|
| Model Name | {model_info.get('name', 'Unknown')} |
| Model Type | {model_info.get('type', 'Unknown')} |
| Version | {model_info.get('version', '1.0')} |
| Training Date | {model_info.get('training_date', 'Unknown')} |
| Task | Binary Classification (Hired / Not Hired) |
| Training Dataset | {model_info.get('training_dataset', 'Synthetic UK Recruitment Data')} |
| N Training Records | {model_info.get('n_train', 'Unknown')} |
| Accuracy | {model_info.get('accuracy', 'Unknown')} |
| ROC-AUC | {model_info.get('roc_auc', 'Unknown')} |
| Explainability Method | {model_info.get('explainability_method', 'Permutation Importance')} |
| Architecture | {model_info.get('architecture', 'N/A')} |

**Features Used:**

{features}

**Features Explicitly Excluded (Protected Characteristics):** Gender, Ethnicity, Age, Disability Status"""

    def _data_audit_section(self, results):
        lines = ["## 2. Data Audit\n", "### 2.1 Representation Analysis\n"]
        for char, groups in results.get("representation", {}).items():
            lines.append(f"**{char.replace('_',' ').title()}**\n")
            lines.append("| Group | Count | % | Status |")
            lines.append("|-------|-------|---|--------|")
            for grp, info in groups.items():
                lines.append(f"| {grp} | {info['count']} | {info['pct']}% | {info['flag']} |")
            lines.append("")

        lines.append("### 2.2 Proxy Feature Detection\n")
        known = results.get("proxy_features", {}).get("known_proxies", {})
        if known:
            lines.append("| Feature | Risk | Reason |")
            lines.append("|---------|------|--------|")
            for feat, info in known.items():
                lines.append(f"| `{feat}` | {info['risk']} | {info['reason']} |")
        else:
            lines.append("No known proxy features detected.")

        lines.append("\n### 2.3 Label Bias\n")
        for char, data in results.get("label_bias", {}).items():
            lines.append(f"**{char.replace('_',' ').title()}** (Overall: {data.get('overall_hire_rate','?')}%)\n")
            lines.append("| Group | Hire Rate | Disparity Ratio | Status |")
            lines.append("|-------|-----------|----------------|--------|")
            for grp, info in data.get("groups", {}).items():
                lines.append(f"| {grp} | {info['hire_rate']}% | {info['disparity_ratio']} | {info['flag']} |")
            lines.append("")

        flags = results.get("summary_flags", [])
        if flags:
            lines.append("### ⚠️ Data Audit Flags\n")
            for flag in flags:
                lines.append(f"- {flag}")
        else:
            lines.append("### ✅ No Critical Data Issues Detected")

        return "\n".join(lines)

    def _fairness_section(self, results):
        lines = ["## 3. Fairness & Bias Metrics\n"]

        compliance = results.get("overall_compliance", {})
        lines.append(f"### Overall Compliance\n\n**{compliance.get('rag_summary','Unknown')}**\n")

        # Show which optional libraries were active
        fairlearn_active = compliance.get("fairlearn_active", False)
        aif360_active    = compliance.get("aif360_active", False)
        lines.append("**Libraries used for this report:**\n")
        lines.append(f"- fairlearn: {'✅ Active' if fairlearn_active else '❌ Not installed'}")
        lines.append(f"- aif360:    {'✅ Active' if aif360_active else '❌ Not installed'}\n")

        for feature, data in results.items():
            if feature == "overall_compliance":
                continue

            lines.append(f"### {feature.replace('_',' ').title()}\n")

            # Built-in demographic parity
            dp = data.get("demographic_parity", {})
            if "demographic_parity_difference" in dp:
                lines.append(f"**Demographic Parity Difference:** {dp['demographic_parity_difference']} {dp.get('rag','')}")
                lines.append(f"  - Highest hire rate: {dp.get('max_hire_rate_group')} ({dp.get('max_rate')}%)")
                lines.append(f"  - Lowest hire rate:  {dp.get('min_hire_rate_group')} ({dp.get('min_rate')}%)\n")

            # DIR table
            dir_data = data.get("disparate_impact_ratio", {})
            if dir_data:
                lines.append("**Disparate Impact Ratios:**\n")
                lines.append("| Group | Hire Rate | Privileged Rate | DIR | Status |")
                lines.append("|-------|-----------|----------------|-----|--------|")
                for grp, info in dir_data.items():
                    lines.append(
                        f"| {grp} | {info.get('hire_rate','?')}% | {info.get('privileged_rate','?')}% "
                        f"| {info.get('dir','?')} | {info.get('rag','?')} |"
                    )
                lines.append("")

            # Fairlearn metrics (if available)
            fl = data.get("fairlearn_metrics", {})
            if fl and "note" not in fl and "error" not in fl:
                lines.append("**Fairlearn Extended Metrics:**\n")
                lines.append(f"  - Demographic Parity Difference: {fl.get('demographic_parity_difference','?')} {fl.get('rag_dpd','')}")
                lines.append(f"  - Equalised Odds Difference:     {fl.get('equalized_odds_difference','?')} {fl.get('rag_eod','')}\n")
            elif fl and "note" in fl:
                lines.append(f"> ℹ️ {fl['note']}\n")

            # AIF360 metrics (if available)
            ai = data.get("aif360_metrics", {})
            if ai and "note" not in ai and "error" not in ai:
                lines.append("**IBM AI Fairness 360 Metrics:**\n")
                lines.append(f"  - Disparate Impact:         {ai.get('disparate_impact','?')}")
                lines.append(f"  - Statistical Parity Diff:  {ai.get('statistical_parity_diff','?')}")
                lines.append(f"  - Consistency Score:        {ai.get('consistency','?')}\n")
            elif ai and "note" in ai:
                lines.append(f"> ℹ️ {ai['note']}\n")

        return "\n".join(lines)

    def _explainability_section(self, summary):
        return f"""## 4. Model Explainability

### 4.1 Global Decision Factors

{summary}

### 4.2 Transparency Statement

This model operates as a decision-support tool. All final hiring decisions must be
reviewed and confirmed by a human HR professional.

In accordance with UK GDPR Article 22, candidates have the right to:
- Request a human review of any automated decision
- Receive an explanation of the decision factors
- Contest decisions made on automated grounds"""

    def _recommendations(self, bias_results, data_results):
        recs = []
        compliance = bias_results.get("overall_compliance", {})

        if compliance.get("red_count", 0) > 0:
            recs.append(
                "🔴 **URGENT:** Disparate impact detected. Suspend automated screening "
                "pending investigation. Consult an employment law specialist. (Equality Act 2010, s.19)"
            )
        if compliance.get("amber_count", 0) > 0:
            recs.append(
                "🟡 **Review Required:** Demographic disparities detected. Conduct manual "
                "review of rejected candidates in affected groups."
            )

        pf = data_results.get("proxy_features", {}).get("known_proxies", {})
        high_risk = [f for f, info in pf.items() if info["risk"] == "HIGH"]
        if high_risk:
            recs.append(
                f"⚠️ **Proxy Features:** Remove high-risk features ({', '.join(high_risk)}) from model inputs."
            )

        if not compliance.get("fairlearn_active"):
            recs.append(
                "📦 **Optional:** Install `fairlearn` for extended fairness metrics: `pip install fairlearn`"
            )
        if not compliance.get("aif360_active"):
            recs.append(
                "📦 **Optional:** Install `aif360` for IBM fairness metrics: `pip install aif360`"
            )

        recs.append("📋 Conduct quarterly bias audits and retain logs for minimum 2 years (ICO guidance).")
        recs.append("👥 Ensure all shortlisting decisions are reviewed by a trained HR professional.")
        recs.append("📢 Publish an AI use statement on your careers page.")

        lines = ["## 5. Recommendations\n"]
        for i, rec in enumerate(recs, 1):
            lines.append(f"{i}. {rec}\n")
        return "\n".join(lines)

    def _regulatory_references(self):
        return """## 6. Regulatory References

| Regulation / Guidance | Relevance |
|----------------------|-----------|
| Equality Act 2010 (s.4, s.19) | Protected characteristics; indirect discrimination |
| UK GDPR (Article 22) | Rights regarding automated decision-making |
| Data Protection Act 2018 | Lawful basis for processing candidate data |
| ICO AI Auditing Framework (2023) | Transparency and explainability requirements |
| EHRC Technical Guidance on Employment | Employer obligations on fair recruitment |
| Employment Practices Code (ICO) | Data protection in recruitment |
| EU AI Act (2024) — for awareness | AI systems in recruitment classified as high-risk |"""

    def _candidate_appendix(self, examples):
        lines = ["## Appendix A: Sample Candidate Explanations\n"]
        for i, exp in enumerate(examples, 1):
            cid      = exp.get("candidate_id", f"Candidate {i}")
            decision = exp.get("decision", "unknown")
            method   = exp.get("method", "")
            explanation = exp.get("plain_english", "No explanation available.")
            lines.append(f"### {cid} — Decision: {decision.upper()} *(Method: {method})*\n")
            lines.append(explanation)
            lines.append("")
        return "\n".join(lines)

    def _footer(self):
        return f"""## Document Control

| Field | Value |
|-------|-------|
| Version | 1.0 |
| Generated By | XAI Audit Toolkit for UK SME Recruitment |
| Generated At | {self.generated_at} |
| Review By | HR Manager / Legal Counsel |

*This document is confidential and intended for internal compliance purposes only.*"""
